version: 2
updates:
  - package-ecosystem: "npm"
    directory: "web/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(web)"
      prefix-development: "chore(web)"
    groups:
      all-dependencies:
        patterns:
          - "*"
