version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      prefix-development: "chore"
      include: "scope"
    groups:
      devDependencies:
        patterns:
          - "devDependencies"
      dependencies:
        patterns:
          - "dependencies"
