#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Obtiene el mensaje de commit
COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

# Define los prefijos permitidos
ALLOWED_PREFIXES="^(feat|chore|fix|docs|style|refactor|perf|test|build|ci|revert|wip|hotfix|release|merge|security|config|ui): [A-Z]"

# Verifica si el mensaje de commit comienza con alguno de los prefijos permitidos
if ! echo "$COMMIT_MSG" | grep -Eq "$ALLOWED_PREFIXES"; then
  echo "Error: El mensaje de commit debe comenzar con uno de los prefijos permitidos y la primera palabra debe estar capitalizada:"
  echo "Prefijos permitidos:"
  echo "- feat"
  echo "- chore"
  echo "- fix"
  echo "- docs"
  echo "- style"
  echo "- refactor"
  echo "- perf"
  echo "- test"
  echo "- build"
  echo "- ci"
  echo "- revert"
  echo "- wip"
  echo "- hotfix"
  echo "- release"
  echo "- merge"
  echo "- security"
  echo "- config"
  echo "- ui"
  echo "Ejemplo de formato: 'feat: Agregar nueva funcionalidad'."
  exit 1
fi
