name: Deploy web app to Render

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  deploy-app:
    if: ${{ contains(github.event.head_commit.message, 'release(frontend):') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploying app release..."
          curl -X POST "$deploy_url"
